### ISSUE TITLE
ResyApi already defined

### ISSUE THREAD

**Issue by ctcavarretta** [Alkaar/resy-booking-bot#100]
Hi Alkaar,

Thanks so much for sharing this code. I'm fairly new to coding but am getting the following error...was wondering if you could help?

The error is in line 13 of ResyApi.scala

ResyApi is already defined as class ResyApi
class ResyApi(resyToken: ResyKeys) {

**Comment by Alkaar** [comment]
I'm guessing since you closed this you were able to figure it out?
