### ISSUE TITLE
Instructions for running it?

### ISSUE THREAD

**Issue by stewx** [Alkaar/resy-booking-bot#11]
Do I just need to run "sbt" to run the server? Are there any other commands required?

**Comment by mohnik1** [comment]
Any updates here?

**Comment by Alkaar** [comment]
Sorry for not keeping up to date on these issues as I've not used nor maintained the bot due to the pandemic. As of now, it seems that Resy updated the API endpoint so the contract is completely different. I have tried to go through the bot to fix things but I haven't gotten around to fixing it completely. Just wanted to make you all aware.

**Comment by mohnik1** [comment]
Ahh thank you for posting! Hope you're safe and healthy. Eagerly awaiting an update to get this running :)

**Comment by Alkaar** [comment]
Hey, so I did finally get around to fixing the bot along with a few minor fixes. Give it a shot and LMK your thoughts.

In terms of running it, I just hit run in IntelliJ. I believe it should figure it out since there is only one main class. If that's not working for you, LMK and I can update the documentation with that info.

**Comment by mohnik1** [comment]
Great to hear! I just redownloaded and built it in IntelliJ & VSC, but cant
get it to run. Any chance you could provide a screenshot?

**Comment by Alkaar** [comment]
@mohnik1 could you provide a bit more context about the error you are seeing when you say you `cant get it to run` so I have a better idea of how to help you.

Also I did a fairly large internal refactor and just pushed a bugfix I accidentally introduce so please try pulling it again.

**Comment by mohnik1** [comment]
@Alkaar I have never used IntelliJ so sorry for my lack of knowledge...but I build it then go to run and receive:

Error: Could not find or load main class com.resy.ResyBookingBot
Caused by: java.lang.ClassNotFoundException: com.resy.ResyBookingBot

**Comment by Alkaar** [comment]
@mohnik1 you have to specify the main entry point of the class to run which lives in `com.resy.ResyBookingBot`. IntelliJ tries to find it for you automatically but sometimes it can't.

![Screen Shot 2022-08-13 at 12 30 49 PM](https://user-images.githubusercontent.com/6472561/184502767-45f5bea2-d3ed-4ee9-8fc2-e1a7379a9242.png)

Also since this is a Scala app, you can run it via sbt by simply typing `sbt` and then typing `run`.

**Comment by Alkaar** [comment]
So when you run `sbt`, it spins up a JVM instance, and executing `run` after that will run the bot inside of that JVM instance. When you run `sbt run` within the same command, it runs whatever command you pass to sbt in that one instance of the JVM and then immediately kills it. So in your case, you are killing the bot before it's even had a chance to complete. 

So run `sbt` as one command, then `run` at the second command.

I've had a lot of people use my bot who are not that familiar with Scala and sbt so I can put some run instructions in the readme for guidance.

**Comment by thierryskoda** [comment]
@Alkaar Thank you! It worked 🙌

**Comment by mohnik1** [comment]
> @mohnik1 you have to specify the main entry point of the class to run which lives in `com.resy.ResyBookingBot`. IntelliJ tries to find it for you automatically but sometimes it can't.
> 
> ![Screen Shot 2022-08-13 at 12 30 49 PM](https://user-images.githubusercontent.com/6472561/184502767-45f5bea2-d3ed-4ee9-8fc2-e1a7379a9242.png)
> 
> Also since this is a Scala app, you can run it via sbt by simply typing `sbt` and then typing `run`.

I'm not sure why its still throwing an error, the directory & class look to be defined correctly. Apologies for being a complete nub at this. Below is what I'm seeing. 

![Screen Shot 2022-08-30 at 9 27 58 PM](https://user-images.githubusercontent.com/101210214/187573035-5d8e698f-b677-48da-9131-eee847e98c8a.png)
![Screen Shot 2022-08-30 at 9 27 45 PM](https://user-images.githubusercontent.com/101210214/187573037-30c1b9f0-9d6d-4763-b9a6-200eeedf81a4.png)
![Screen Shot 2022-08-30 at 9 27 13 PM](https://user-images.githubusercontent.com/101210214/187573038-6afbe7df-12db-4a73-ac86-820532f61381.png)

**Comment by Alkaar** [comment]
I don't think you've set up IntelliJ correctly. If you notice, my folder hierarchy looks slightly different. Notably the scala folder is blue. This tells IntelliJ that the source code lives there. Yours is not set up that way so likely that is at least one of the reasons IntelliJ can't find the main class.

Folder Hierarchy
![Screen Shot 2022-08-30 at 9 43 19 PM](https://user-images.githubusercontent.com/6472561/187574442-ea5f9735-4a47-4473-9f0f-54d716eec6e5.png)

Below can be found under File ➡️  Project Structure ➡️ Project Settings ➡️ Modules ➡️ Sources
![Screen Shot 2022-08-30 at 9 43 01 PM](https://user-images.githubusercontent.com/6472561/187574449-8b818e4b-c92b-41c8-a5c9-45f6be3c61bf.png)

**Comment by mohnik1** [comment]
@Alkaar Thank you, made some progress here...looks like the folder hierarchy was the main issue. Loaded a new project & defined the sources, looks to be configured correctly. Only receiving a build error on timing formats now. 

![Screen Shot 2022-08-30 at 10 40 33 PM](https://user-images.githubusercontent.com/101210214/187580858-545a2883-b9a0-472c-92b4-d95223b5a674.png)
![Screen Shot 2022-08-30 at 10 40 27 PM](https://user-images.githubusercontent.com/101210214/187580860-fef29e78-1917-451f-91df-8f3d44678ebd.png)

**Comment by Alkaar** [comment]
See 👉 https://github.com/Alkaar/resy-booking-bot/issues/27#issuecomment-1219538418

**Comment by Alkaar** [comment]
I haven't heard back here but if no issues, I'm going to be closing this. I also added more instructions in the readme. Feel free to reopen if there are any more questions regarding this.

**Comment by Alkaar** [comment]
FYI since a lot of people had some confusion around how to set the reservation time and table type, I made a change to hopefully make this a little bit more clear 👉 https://github.com/Alkaar/resy-booking-bot/pull/54

**Comment by btseng0102** [comment]
i made the scala folder my source and it resolved the issue of com.resy not being found, but now the "ResyBookingBot' portion of "com.resy.ResyBookingBot" is showing an error and I'm not sure how to fix it.

![CleanShot 2023-07-19 at 23 41 30](https://github.com/Alkaar/resy-booking-bot/assets/140049494/bdb82b0a-1cd5-4133-a036-2821409ea11b)
![CleanShot 2023-07-19 at 23 42 03](https://github.com/Alkaar/resy-booking-bot/assets/140049494/65b581b5-2154-4277-9769-45afe41d4086)

**Comment by Alkaar** [comment]
I wrote up a [Wiki](https://github.com/Alkaar/resy-booking-bot/wiki) on getting started since a lot of people were asking questions on this. Specifically, see if the [troubleshooting](https://github.com/Alkaar/resy-booking-bot/wiki/Getting-Started#troubleshooting-%EF%B8%8F-) section helps
