### ISSUE TITLE
Run using IntelliJ

### ISSUE THREAD

**Issue by gibdr7** [Alkaar/resy-booking-bot#116]
I've looked through previous issues and the README, haven't seen anyone with this issue. I prefer VSC, but using IntelliJ to be consistent with your instructions. I'm trying to configure com. ,  but get am unable to fill in the Main class. 

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/57686989/236817645-474e5acf-ac22-4378-9d54-eb94998a10e1.png">

Also, if I try "sbt" in terminal, I get the below error:
`java.lang.RuntimeException: Path '.../target/config-classes' contains separator ':'`

Any help would be much appreciated!

**Comment by eftehassanpp** [comment]
in VSC its simple and easy.
make sure you have java  SDK installed as well as Scala installed.
then just in vs code in project run folder open terminal type simply sbt
then run

**Comment by c17mr** [comment]
I am also having this issue and cannot find a good answer or get IntelliJ to profile it correctly and run.
