### ISSUE TITLE
Unable to book

### ISSUE THREAD

**Issue by Champagnesloppy** [Alkaar/resy-booking-bot#128]
Testing on available reservations to ensure it's working but I'm unable to book restaurants that have slots available? Any ideas? 
Thanks 

[INFO ] 2023-06-13 13:40:10.168-04:00 ResyBookingBot$:16 - Starting Resy Booking Bot
[INFO ] 2023-06-13 13:40:10.928-04:00 ResyBookingBot$:45 - Next snipe time: 2023-06-13T13:41:00.000-04:00
[INFO ] 2023-06-13 13:40:10.928-04:00 ResyBookingBot$:46 - Sleeping for 0 hours, 0 minutes, and 47 seconds
[INFO ] 2023-06-13 13:40:58.024-04:00 ResyBookingWorkflow:18 - Taking the shot...
[INFO ] 2023-06-13 13:40:58.025-04:00 ResyBookingWorkflow:19 - (҂‾ ▵‾)︻デ═一 (˚▽˚’!)/
[INFO ] 2023-06-13 13:40:58.025-04:00 ResyBookingWorkflow:20 - Attempting to snipe reservation
[INFO ] 2023-06-13 13:40:59.012-04:00 ResyClient:197 - Config Id: rgs://resy/60029/1677974/2/2023-06-23/2023-06-23/18:00:00/2/Dining Room
[INFO ] 2023-06-13 13:40:59.068-04:00 ResyClient:79 - Payment Method Id: 17750488
[INFO ] 2023-06-13 13:40:59.068-04:00 ResyClient:88 - Book Token: o0Dvm4YN02dzNWQdugkThqPB|aBeCDb9nw6pIJte4dM1eSUb20tJOg0dHK2I|ZbSN3gQc3fTvPUQTJHfFQmApXgmlPhKYefVMBUu2enuGzWJ6bOtUhcBt|6lYpCR|jxczMNJvvtN95MiuxRMdwGuLmqEowRxMd7kPyd0Bu6Xgk4FR9FS88REZ64Ty5K2LXE13mql|nxGdi0kD4aX8x01T4xqrivJx7zg82VNUirAnW0n6hBQAlNjZOzrEKD661cWLCyQlDJ17HNn96rb_YDG3VmJnAq9XrGZ8|IoKGC4WIVaBQH0qMj7kZFfWkAu8d|M_qL0976EaMG635C_NLiCl7Lz9onXU5lDDPWtdZru|UEJzWw9kNF9mHBjjqSkbUjKf0Zna9q9enFIEcDYR1VNXu1Be4AEsZwRvU_J4Yy59qeKfW3lZAFOmO7ld2zsEdq5PmBkoFh1wlUh1ThFl8nLBM2g5EuHWaGUg8PeitYZl32OfZV|xjNCXG9_5zErioUgJK|8|N6upktTN8kJVIlczU9KrEAq8|59HguM3x_|_ZJxrCAipS9kjsvsueSM0ZiK85aUnKlAGTl0uqgsz4CCQ5XF|5CaFizKMn6u12IUHAMk60SW8RomR|_nga7hhfKJ9ehPWfFoPYRUicJf0uGmJHszmk5Z4GDMsCQ5jnzjO8dDpQG5oget6WtV2xxmkM85-69861b5cd547b7231d6b8193849ca38ca7d043c93f30fe4dd74d42c8
[INFO ] 2023-06-13 13:40:59.099-04:00 ResyClient:136 - Missed the shot!
[INFO ] 2023-06-13 13:40:59.099-04:00 ResyClient:137 - ┻━┻ ︵ \(°□°)/ ︵ ┻━┻
[INFO ] 2023-06-13 13:40:59.099-04:00 ResyClient:138 - Reservation no longer available
[INFO ] 2023-06-13 13:40:59.100-04:00 ResyBookingWorkflow:18 - Taking the shot...
[INFO ] 2023-06-13 13:40:59.100-04:00 ResyBookingWorkflow:19 - (҂‾ ▵‾)︻デ═一 (˚▽˚’!)/
[INFO ] 2023-06-13 13:40:59.100-04:00 ResyBookingWorkflow:20 - Attempting to snipe reservation

**Comment by jaipalsilla** [comment]
Hey, I am trying to test the bot by also making a reservation that I know is available but to no luck. How are you able to do it?
