### ISSUE TITLE
implement http proxy

### ISSUE THREAD

**Issue by eftehassanpp** [Alkaar/resy-booking-bot#134]
implement http proxy so i can add proxy in the config file and the bot will use that proxy for requests.
i have tried to find solution for http proxy on AhcClient but most solutions gives error. so please implement a solution for using proxy

**Comment by Alkaar** [comment]
Is there a reason you opened this and then immediately closed it?

**Comment by eftehassanpp** [comment]
I didn't close it. It might be in mistake . But if you could implement
proxy that would be great
