### ISSUE TITLE
Specify timezone the server should run on

### ISSUE THREAD

**Issue by adamduren** [Alkaar/resy-booking-bot#15]
This is a cool project and I am looking to use it. Should the server run on UTC or some other specific timezone?

**Comment by Alkaar** [comment]
So I believe reservations become available based on how the restuarant has it configured so you just have to ensure it snipes as soon as the reservations become available. For me it's EST but not sure what it would look like for you.

**Comment by Alkaar** [comment]
Updated the documentation on this here 👉 https://github.com/Alkaar/resy-booking-bot/pull/37

Will close out this issue if no concerns
