### ISSUE TITLE
error: illegal start of definition "package"

### ISSUE THREAD

**Issue by amandajmunch** [Alkaar/resy-booking-bot#16]
error: illegal start of definition "package com.resy"

What's the workaround for this? Thank you! Hope to get this working

**Comment by Alkaar** [comment]
Hey @amandajmunch, give this a shot again, I updated some libraries and the code to work with the new Resy API. LMK if you are still having issues.

**Comment by Alkaar** [comment]
I didn't hear back if this was still an issue for you or not but since I've refactored the code significantly and no one else has brought this up, I'm going to close this issue out. Feel free to reopen this if it's still a blocker for you.
