### ISSUE TITLE
scala.NotImplementedError: an implementation is missing

### ISSUE THREAD

**Issue by bigdogvision-jeff** [Alkaar/resy-booking-bot#28]
I'm getting this error when i'm trying to run the project

➜  resy-booking-bot git:(master) ✗ sbt run
[info] welcome to sbt 1.7.1 (Homebrew Java 18.0.2)
[info] loading settings for project resy-booking-bot-build from plugins.sbt ...
[info] loading project definition from /Users/jeffreydrakos/Sites/random/resy-booking-bot/project
[info] loading settings for project root from build.sbt ...
[info] set current project to resy-booking-bot (in build file:/Users/jeffreydrakos/Sites/random/resy-booking-bot/)
[info] running com.resy.ResyBookingBot 
[error] scala.NotImplementedError: an implementation is missing
[error] 	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:344)
[error] 	at com.resy.ResyBookingBot$.<clinit>(ResyBookingBot.scala:30)
[error] 	at com.resy.ResyBookingBot.main(ResyBookingBot.scala)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) scala.NotImplementedError: an implementation is missing
[error] Total time: 1 s, completed Aug 15, 2022, 8:56:13 PM

Any thoughts?

**Comment by Alkaar** [comment]
If you read through the documentation, it will tell you what values you need to set in order for the bot to work. If you read the stack trace, it actually points exactly to where a value is missing for you. The bot can't know what reservation to snipe unless you define it.

**Comment by Alkaar** [comment]
Haven't heard back on this so closing this issue. Feel free to reopen if you have any more questions.

**Comment by Alkaar** [comment]
Ended up changing this to make this a bit clearer

https://github.com/Alkaar/resy-booking-bot/pull/54
