### ISSUE TITLE
resTimeTypes

### ISSUE THREAD

**Issue by rmize** [Alkaar/resy-booking-bot#31]
Would someone mind providing an example of how this variable should be formatted? I am getting a type mismatch error. Thanks!

**Comment by rmize** [comment]
For example, I've tried this: resTimeTypes = ("17:00:00", "Patio")

**Comment by Alkaar** [comment]
No worries. Actually, someone else asked me [the same question](https://github.com/Alkaar/resy-booking-bot/issues/27#issuecomment-1214588270) which I answered here 👉  https://github.com/Alkaar/resy-booking-bot/issues/27#issuecomment-1219538418

**Comment by rmize** [comment]
Thank you!

**Comment by rmize** [comment]
Thanks again I got the code running. Unfortunately everytime I try and snipe a reservation it is giving feedback that no reservation available. Have plugged in the below, wonder if I am doing something wrong. Confirming I am trying for a date where every single time  is open to test.

  private val resDetails = ReservationDetails(
    // Date of the reservation in YYYY-MM-DD format; note you do not need 0 in front of single digit
    date = "2022/09/09",
    // Size of the party reservation
    partySize = 2,
    // Unique identifier of the restaurant where you want to make the reservation
    venueId = 10362,
    // Priority list of reservation times and table types. Time is in military time HH:MM:SS format.
    // If no preference on table type, then simply don't set it.
    resTimeTypes = {
      Seq(ReservationTimeType("18:15:00"))
    }
  )

  private val snipeTime = SnipeTime(
    // Hour of the day when reservations become available and when you want to snipe
    hours = 19,
    // Minute of the day when reservations become available and when you want to snipe
    minutes = 32
  )

**Comment by Alkaar** [comment]
The date format is wrong. Reread the comment above it for the correct format. Also it says `note you do not need 0 in front of single digit` which is not in the actual code on master so I can't confirm if that is actually a true statement or not.

**Comment by rmize** [comment]
Thank you, you are correct

**Comment by Alkaar** [comment]
FYI since a lot of people had some confusion around how to set the reservation time and table type, I made a change to hopefully make this a little bit more clear 👉 https://github.com/Alkaar/resy-booking-bot/pull/54
