### ISSUE TITLE
How do you specify target time and table type?

### ISSUE THREAD

**Issue by Boh1** [Alkaar/resy-booking-bot#35]
I've been struggling through understanding how to specify the desired reservation time and table type (or simply no table preference).

I populate **resTimeTypes**  with various values, but keep getting compilation errors like `required: com.resy.ReservationTimeType`. 

I get that this gets converted to a sequence later, but what am I missing in terms of proper format for this value?

**Comment by Alkaar** [comment]
Check out this link where I answered this question previously 👉 https://github.com/Alkaar/resy-booking-bot/issues/27#issuecomment-1219538418

**Comment by Boh1** [comment]
Thanks, that does it!

**Comment by Alkaar** [comment]
FYI since a lot of people had some confusion around how to set the reservation time and table type, I made a change to hopefully make this a little bit more clear 👉 https://github.com/Alkaar/resy-booking-bot/pull/54
