### ISSUE TITLE
Clarification on resTimeTypes format

### ISSUE THREAD

**Issue by permitanyany** [Alkaar/resy-booking-bot#43]
Hi,
I'm brand new with Scala and was hoping to get some clarification on the format of the resTimeTypes variable.  I've tried a ton of different options and keep coming back to the same type mismatch issue.  Thanks in advance.

**Comment by Alkaar** [comment]
Someone else actually asked this question which I answered here 👉 https://github.com/Alkaar/resy-booking-bot/issues/27#issuecomment-1219538418

**Comment by permitanyany** [comment]
Great, thank you very much!

**Comment by Alkaar** [comment]
FYI since a lot of people had some confusion around how to set the reservation time and table type, I made a change to hopefully make this a little bit more clear 👉 https://github.com/Alkaar/resy-booking-bot/pull/54
