### ISSUE TITLE
Struggling to find auth token and restaurant id any help?

### ISSUE THREAD

**Issue by Sashaz55** [Alkaar/resy-booking-bot#51]
Know this might not be the best place but does anyone have any tips on finding the auth token and restaurant id? For some reason can't find those. Any help?

**Comment by Alkaar** [comment]
Was the readme and the comments in the config file not enough to be able to find it?

**Comment by Sashaz55** [comment]
Yeah. A

**Comment by Sashaz55** [comment]
Yeah wasn’t able to find it. Looking where it says in the readme.

**Comment by Alkaar** [comment]
For the auth token, load the restaurant page. Look at the `/find` API. At the bottom of the headers section you should see `x-resy-auth-token`. The `venue_id` can be found in the payload of the same API call.

**Comment by hahacharlie** [comment]
I am also having a big issue with the `resy-auth-token` here. I am getting this `invalid literal number` error message after I copy-paste the `resy-auth-token` value from my web console to the config file. Do you have any clue what's causing this issue? Much appreciated!

**Comment by Alkaar** [comment]
Hi @Sashaz55, just following up if you were able to find the values you needed. I also made a PR to improve the documentation a bit so would love some feedback on it.

https://github.com/Alkaar/resy-booking-bot/tree/docs/improve-documentation

**Comment by Alkaar** [comment]
Going to close this since I've not heard a response. Hopefully, the documentation change in my PR is a little bit clearer.
