### ISSUE TITLE
how do i access the resy API?

### ISSUE THREAD

**Issue by nitram12** [Alkaar/resy-booking-bot#58]
struggling to find the api key and auth token. thanks.

**Comment by Alkaar** [comment]
I made a PR below to improve the documentation a bit. Can you see if this answers your question and if not, perhaps I can improve the documentation before I merge it.

https://github.com/Alkaar/resy-booking-bot/tree/docs/improve-documentation

**Comment by nitram12** [comment]
i am just having trouble making calls to the resy api within the web console.. maybe i am overcomplicating

**Comment by Alkaar** [comment]
You literally just open the web console and just click around the website. The calls will show up and there's a filter section at the top to look for specific API calls.

**Comment by nitram12** [comment]
yeah was overcomplicating, solved

**Comment by rkass** [comment]
Also wondering how to get an API key. The docs linked above lead to a broken link. Thanks!

**Comment by rkass** [comment]
> Also wondering how to get an API key. The docs linked above lead to a broken link. Thanks!

NVM, read the docs again, it's pretty clear.
