### ISSUE TITLE
Variables still exposed via console?

### ISSUE THREAD

**Issue by creeront** [Alkaar/resy-booking-bot#6]
I opened the chrome web  console, but can't manage to find any of the variables you mentioned.  Are you aware if they're still exposed? 

Thanks.

**Comment by bdelo** [comment]
If you look at any network fetch request (`/calendar` is a good one) and go to the headers tab you can still find the information. 

Scroll to the bottom of the of the headers tab to the `query parameters` section. Here you'll find the auth token, venue id, etc. 

Scroll back up to the `request headers` section of the same tab, and under `authorization` youll find the api key

**Comment by derfong** [comment]
I just wanted to follow up on this if you were able to figure it out @creeront.  I know it's a bit hard to find but the variables are all there.  I could try adding more specific instructions in the readme to make it easier to find.

**Comment by creeront** [comment]
I did figure it out. Thanks!

**Comment by zeyademam** [comment]
I was wondering how to get an api key? I figured out the auth_token and venue id following @bdelo 's suggestion. But cannot figure out the api key. Do I have to email them?
