### ISSUE TITLE
Request: Multiple Wakeup and Snipe Sessions

### ISSUE THREAD

**Issue by justinishikawa** [Alkaar/resy-booking-bot#62]
Great program, thank you for developing it.

I think it would be helpful to have the ability to set the bot to periodically check if a reservation is there on some cadence and if it is, grab it, if not back to sleep until the next time. It would also have to have some functionality that if there was a success to kill itself permanently

**Comment by Alkaar** [comment]
I've considered something like this but for reasons, I opted to not implement this. See https://github.com/Alkaar/resy-booking-bot/issues/52#issuecomment-1272680346
