### ISSUE TITLE
Time slot ordering

### ISSUE THREAD

**Issue by martykebke** [Alkaar/resy-booking-bot#66]
Thank you - this is great and I got it up in running pretty quickly with minimal experience.

I was hoping to just confirm how the time slot ordering works? Is the code reading from left to right w/ priority, or is it randomized in terms of just selecting any reservation specified that's available?

For example if I wanted 7pm but I was okay with 6pm, and I put in 7pm and then 6pm, would it prioritize 7pm first ? 

Thanks!

**Comment by Alkaar** [comment]
> For example if I wanted 7pm but I was okay with 6pm, and I put in 7pm and then 6pm, would it prioritize 7pm first ?

Yes, it would prioritize 7 PM first. The documentation mentions it's a priority list so this is what I meant. The priority is top-down so it tries the first time slot, then the second, and so on until it gets a hit.

It sounded like you were just clarifying your understanding but if you felt the documentation wasn't clear, LMK so I can improve it.

**Comment by martykebke** [comment]
Thank you for clarifying. It does say priority list and I think clear enough, I just wanted to confirm as my first number of attempts kept getting hit pretty far down may list so just wanted to confirm my understanding was correct. Thanks again!

**Comment by Alkaar** [comment]
So there is a log4j file where you can flip the logging to debug to show you more detail. I purposely leave this off because it can print so much that it actually slows down the bot. Something to try if you actually what to see what the restaurants return as available compared to your priority list.
