### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by jacklesliewise** [Alkaar/resy-booking-bot#68]
Nice job on this - I used it yesterday to book somewhere and worked like a charm.

Could you put up a donation link so we can send you a thanks? I was looking for a https://www.buymeacoffee.com/ link but couldn't see one

**Comment by Alkaar** [comment]
Hey! Really appreciate the thought! ❤️ 

I created a Ko-fi one. Want to integrate it nicely into the readme/GitHub but in the mean time, here you go.

https://ko-fi.com/alkaar

**Comment by Alkaar** [comment]
And finally made the link fit nicely into GitHub and the readme 👉  https://github.com/Alkaar/resy-booking-bot/pull/69

Thanks for the suggestion!
