### ISSUE TITLE
ResyBookingBot is already defined as object ResyBookingBot

### ISSUE THREAD

**Issue by crookedbans** [Alkaar/resy-booking-bot#76]
Thanks so much for this code!! This is so awesome and would LOVE to have this work.

Sorry, I am new to scala/intellig. Google says it might have to do with sources of sbt/intellig, but that didnt seem to work..

Seeing the same error in sbt shell too. Attaching screenshots of configs and project structure. Any idea how to fix this?

<img width="1027" alt="Screen Shot 2022-12-27 at 8 20 11 AM" src="https://user-images.githubusercontent.com/36647724/209672977-5da119aa-07d1-46b6-a351-4f5b246ed644.png">
<img width="293" alt="Screen Shot 2022-12-27 at 8 19 50 AM" src="https://user-images.githubusercontent.com/36647724/209673000-55583c6c-6820-4056-99e7-2c9c768a0028.png">
<img width="296" alt="Screen Shot 2022-12-27 at 8 17 38 AM" src="https://user-images.githubusercontent.com/36647724/209673009-99ecfc30-e127-4aaa-bb88-923f7af9eaa5.png">

**Comment by crookedbans** [comment]
I fixed this by removing the Scalatest config and removing any of the python code that got mixed up in there.

Bot looks to be working now, but having trouble finding reservation (coming back saying empty when it is not in actuality). Might be an issue with venueID or others?

**Comment by crookedbans** [comment]
If helpful for others -- venueid most easily found in the string venue?id= as opposed to request header in network console.

**Comment by crookedbans** [comment]
Sorry for keep commenting, but last thing from me. Some restaurants are delaying release times and doing at random minutes/seconds. Is there a way for this to run every 10 seconds for say 30minutes? This is a trend we are seeing in Miami, NYC, etc etc

**Comment by Alkaar** [comment]
I'd be curious what restaurant is doing this. I purposely did not add that feature because I didn't want to hammer the endpoint all day as that would make them crack down on bots.

**Comment by Alkaar** [comment]
On the restaurant delaying release times, it was also brought up in this issue 👉 https://github.com/Alkaar/resy-booking-bot/issues/82

Going to close this issue out since it seems everything has been addressed here or can be discussed in the corresponding issue linked above.
