### ISSUE TITLE
Error during run

### ISSUE THREAD

**Issue by EddiOS42** [Alkaar/resy-booking-bot#99]
I'm getting a few Expected errors when trying to run the file.
![Screenshot 2023-03-19 at 5 21 57 PM](https://user-images.githubusercontent.com/90667316/226219835-65802823-c945-4f00-af47-98c191215609.jpg)

**Comment by Alkaar** [comment]
Per the documentation, first type `sbt` then type `run`

**Comment by EddiOS42** [comment]
Thanks, worked nicely. Also, should I set the snipe time a little prior to reservations being released? It said it missed the shot today.

**Comment by Alkaar** [comment]
I already configured the bot to snipe a few seconds before your snipe time so you don't need to worry about that. Also, there is currently a breaking bug with the bot. Someone opened a PR to fix it which should hopefully be merged soon 👉 https://github.com/Alkaar/resy-booking-bot/pull/104
